module.exports = {
  purge: {
    content: ['./src/**/*.vue'],
    options: {
      whitelist: [
        'bg-red-400',
        'bg-red-500',
        'text-red-100',
        'text-red-200',
        'text-red-800',
        'text-red-900',
        'bg-blue-400',
        'bg-blue-500',
        'text-blue-100',
        'text-blue-200',
        'text-blue-800',
        'text-blue-900',
        'bg-orange-400',
        'bg-orange-500',
        'text-orange-100',
        'text-orange-200',
        'text-orange-800',
        'text-orange-900',
        'hover:bg-red-400',
        'hover:bg-red-500',
        'hover:text-red-100',
        'hover:text-red-200',
        'hover:text-red-800',
        'hover:text-red-900',
        'hover:bg-blue-400',
        'hover:bg-blue-500',
        'hover:text-blue-100',
        'hover:text-blue-200',
        'hover:text-blue-800',
        'hover:text-blue-900',
        'hover:bg-orange-400',
        'hover:bg-orange-500',
        'hover:text-orange-100',
        'hover:text-orange-200',
        'hover:text-orange-800',
        'hover:text-orange-900',
      ],
    },
  },
  theme: {
    extend: {},
  },
  variants: {},
  plugins: [],
};
